# Aggregates the whole suite so `bin/test` covers everything in one run.
require "tests/diver_tests.rb"
require "tests/sloppy_scalar_tests.rb"
require "tests/weed_tests.rb"
require "tests/sand_tile_tests.rb"
require "tests/fog_of_war_tests.rb"
require "tests/panel_tests.rb"
require "tests/game_tests.rb"
require "tests/surface_tests.rb"
require "tests/oxygen_tests.rb"
require "tests/game_over_tests.rb"
require "tests/sprint_tests.rb"
require "tests/intro_tests.rb"
